webtalk_init -webtalk_dir C:/Users/lenovo/PROJECT-9_D_Flip_Flop/PROJECT-9_D_Flip_Flop.sim/sim_1/behav/xsim/xsim.dir/D_FF_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Jul 19 14:50:03 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c5a3ad3c-cc21-4b1e-8cb9-f68c9fe24496" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "25745f80b40f4bfbbc1e61ba3d1163d8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1896 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "30 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8480_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2870498164 -regid "" -xml C:/Users/lenovo/PROJECT-9_D_Flip_Flop/PROJECT-9_D_Flip_Flop.sim/sim_1/behav/xsim/xsim.dir/D_FF_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/lenovo/PROJECT-9_D_Flip_Flop/PROJECT-9_D_Flip_Flop.sim/sim_1/behav/xsim/xsim.dir/D_FF_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/lenovo/PROJECT-9_D_Flip_Flop/PROJECT-9_D_Flip_Flop.sim/sim_1/behav/xsim/xsim.dir/D_FF_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
