# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/lenovo/PROJECT-20_GPIO_AND_UART_MICROBLAZE/PROJECT-20_GPIO_AND_UART_MICROBLAZE.srcs/sources_1/bd/GPIO_UART/ip/GPIO_UART_axi_gpio_1_0/GPIO_UART_axi_gpio_1_0.xci
# IP: The module: 'GPIO_UART_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lenovo/PROJECT-20_GPIO_AND_UART_MICROBLAZE/PROJECT-20_GPIO_AND_UART_MICROBLAZE.srcs/sources_1/bd/GPIO_UART/ip/GPIO_UART_axi_gpio_1_0/GPIO_UART_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'GPIO_UART_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/lenovo/PROJECT-20_GPIO_AND_UART_MICROBLAZE/PROJECT-20_GPIO_AND_UART_MICROBLAZE.srcs/sources_1/bd/GPIO_UART/ip/GPIO_UART_axi_gpio_1_0/GPIO_UART_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'GPIO_UART_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/lenovo/PROJECT-20_GPIO_AND_UART_MICROBLAZE/PROJECT-20_GPIO_AND_UART_MICROBLAZE.srcs/sources_1/bd/GPIO_UART/ip/GPIO_UART_axi_gpio_1_0/GPIO_UART_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'GPIO_UART_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/lenovo/PROJECT-20_GPIO_AND_UART_MICROBLAZE/PROJECT-20_GPIO_AND_UART_MICROBLAZE.srcs/sources_1/bd/GPIO_UART/ip/GPIO_UART_axi_gpio_1_0/GPIO_UART_axi_gpio_1_0.xci
# IP: The module: 'GPIO_UART_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lenovo/PROJECT-20_GPIO_AND_UART_MICROBLAZE/PROJECT-20_GPIO_AND_UART_MICROBLAZE.srcs/sources_1/bd/GPIO_UART/ip/GPIO_UART_axi_gpio_1_0/GPIO_UART_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'GPIO_UART_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/lenovo/PROJECT-20_GPIO_AND_UART_MICROBLAZE/PROJECT-20_GPIO_AND_UART_MICROBLAZE.srcs/sources_1/bd/GPIO_UART/ip/GPIO_UART_axi_gpio_1_0/GPIO_UART_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'GPIO_UART_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/lenovo/PROJECT-20_GPIO_AND_UART_MICROBLAZE/PROJECT-20_GPIO_AND_UART_MICROBLAZE.srcs/sources_1/bd/GPIO_UART/ip/GPIO_UART_axi_gpio_1_0/GPIO_UART_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'GPIO_UART_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
