# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/boolean.xdc

# Block Designs: bd/BLE_Decryption/BLE_Decryption.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BLE_Decryption || ORIG_REF_NAME==BLE_Decryption} -quiet] -quiet

# IP: bd/BLE_Decryption/ip/BLE_Decryption_UART_Rx_0_0/BLE_Decryption_UART_Rx_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BLE_Decryption_UART_Rx_0_0 || ORIG_REF_NAME==BLE_Decryption_UART_Rx_0_0} -quiet] -quiet

# IP: bd/BLE_Decryption/ip/BLE_Decryption_Seven_seg_0_0/BLE_Decryption_Seven_seg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BLE_Decryption_Seven_seg_0_0 || ORIG_REF_NAME==BLE_Decryption_Seven_seg_0_0} -quiet] -quiet

# IP: bd/BLE_Decryption/ip/BLE_Decryption_Seven_seg_1_0/BLE_Decryption_Seven_seg_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BLE_Decryption_Seven_seg_1_0 || ORIG_REF_NAME==BLE_Decryption_Seven_seg_1_0} -quiet] -quiet

# IP: bd/BLE_Decryption/ip/BLE_Decryption_Decrypter_0_1/BLE_Decryption_Decrypter_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BLE_Decryption_Decrypter_0_1 || ORIG_REF_NAME==BLE_Decryption_Decrypter_0_1} -quiet] -quiet

# IP: bd/BLE_Decryption/ip/BLE_Decryption_UART_Tx_0_0/BLE_Decryption_UART_Tx_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BLE_Decryption_UART_Tx_0_0 || ORIG_REF_NAME==BLE_Decryption_UART_Tx_0_0} -quiet] -quiet

# XDC: bd/BLE_Decryption/BLE_Decryption_ooc.xdc
