# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/boolean.xdc

# Block Designs: bd/UART_secure_BLE/UART_secure_BLE.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==UART_secure_BLE || ORIG_REF_NAME==UART_secure_BLE} -quiet] -quiet

# IP: bd/UART_secure_BLE/ip/UART_secure_BLE_UART_Rx_0_0/UART_secure_BLE_UART_Rx_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==UART_secure_BLE_UART_Rx_0_0 || ORIG_REF_NAME==UART_secure_BLE_UART_Rx_0_0} -quiet] -quiet

# IP: bd/UART_secure_BLE/ip/UART_secure_BLE_Seven_seg_0_1/UART_secure_BLE_Seven_seg_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==UART_secure_BLE_Seven_seg_0_1 || ORIG_REF_NAME==UART_secure_BLE_Seven_seg_0_1} -quiet] -quiet

# IP: bd/UART_secure_BLE/ip/UART_secure_BLE_Encryption_logic_0_0/UART_secure_BLE_Encryption_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==UART_secure_BLE_Encryption_logic_0_0 || ORIG_REF_NAME==UART_secure_BLE_Encryption_logic_0_0} -quiet] -quiet

# IP: bd/UART_secure_BLE/ip/UART_secure_BLE_UART_Tx_0_0/UART_secure_BLE_UART_Tx_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==UART_secure_BLE_UART_Tx_0_0 || ORIG_REF_NAME==UART_secure_BLE_UART_Tx_0_0} -quiet] -quiet

# IP: bd/UART_secure_BLE/ip/UART_secure_BLE_Seven_seg_1_0/UART_secure_BLE_Seven_seg_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==UART_secure_BLE_Seven_seg_1_0 || ORIG_REF_NAME==UART_secure_BLE_Seven_seg_1_0} -quiet] -quiet

# XDC: bd/UART_secure_BLE/UART_secure_BLE_ooc.xdc
