# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/boolean.xdc

# Block Designs: bd/BLE_UART/BLE_UART.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BLE_UART || ORIG_REF_NAME==BLE_UART} -quiet] -quiet

# IP: bd/BLE_UART/ip/BLE_UART_Seven_seg_0_0/BLE_UART_Seven_seg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BLE_UART_Seven_seg_0_0 || ORIG_REF_NAME==BLE_UART_Seven_seg_0_0} -quiet] -quiet

# IP: bd/BLE_UART/ip/BLE_UART_UART_Rx_0_0/BLE_UART_UART_Rx_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BLE_UART_UART_Rx_0_0 || ORIG_REF_NAME==BLE_UART_UART_Rx_0_0} -quiet] -quiet

# IP: bd/BLE_UART/ip/BLE_UART_UART_Rx_1_0/BLE_UART_UART_Rx_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BLE_UART_UART_Rx_1_0 || ORIG_REF_NAME==BLE_UART_UART_Rx_1_0} -quiet] -quiet

# IP: bd/BLE_UART/ip/BLE_UART_Seven_seg_1_0/BLE_UART_Seven_seg_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BLE_UART_Seven_seg_1_0 || ORIG_REF_NAME==BLE_UART_Seven_seg_1_0} -quiet] -quiet

# XDC: bd/BLE_UART/BLE_UART_ooc.xdc
