# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/boolean.xdc

# Block Designs: bd/GPIO_UART/GPIO_UART.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==GPIO_UART || ORIG_REF_NAME==GPIO_UART} -quiet] -quiet

# IP: bd/GPIO_UART/ip/GPIO_UART_microblaze_0_0/GPIO_UART_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==GPIO_UART_microblaze_0_0 || ORIG_REF_NAME==GPIO_UART_microblaze_0_0} -quiet] -quiet

# IP: bd/GPIO_UART/ip/GPIO_UART_axi_gpio_0_0/GPIO_UART_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==GPIO_UART_axi_gpio_0_0 || ORIG_REF_NAME==GPIO_UART_axi_gpio_0_0} -quiet] -quiet

# IP: bd/GPIO_UART/ip/GPIO_UART_axi_uartlite_0_0/GPIO_UART_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==GPIO_UART_axi_uartlite_0_0 || ORIG_REF_NAME==GPIO_UART_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/GPIO_UART/ip/GPIO_UART_mdm_1_0/GPIO_UART_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==GPIO_UART_mdm_1_0 || ORIG_REF_NAME==GPIO_UART_mdm_1_0} -quiet] -quiet

# IP: bd/GPIO_UART/ip/GPIO_UART_rst_mclk_100M_0/GPIO_UART_rst_mclk_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==GPIO_UART_rst_mclk_100M_0 || ORIG_REF_NAME==GPIO_UART_rst_mclk_100M_0} -quiet] -quiet

# IP: bd/GPIO_UART/ip/GPIO_UART_microblaze_0_axi_periph_0/GPIO_UART_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==GPIO_UART_microblaze_0_axi_periph_0 || ORIG_REF_NAME==GPIO_UART_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/GPIO_UART/ip/GPIO_UART_xbar_0/GPIO_UART_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==GPIO_UART_xbar_0 || ORIG_REF_NAME==GPIO_UART_xbar_0} -quiet] -quiet

# IP: bd/GPIO_UART/ip/GPIO_UART_dlmb_v10_0/GPIO_UART_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==GPIO_UART_dlmb_v10_0 || ORIG_REF_NAME==GPIO_UART_dlmb_v10_0} -quiet] -quiet

# IP: bd/GPIO_UART/ip/GPIO_UART_ilmb_v10_0/GPIO_UART_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==GPIO_UART_ilmb_v10_0 || ORIG_REF_NAME==GPIO_UART_ilmb_v10_0} -quiet] -quiet

# IP: bd/GPIO_UART/ip/GPIO_UART_dlmb_bram_if_cntlr_0/GPIO_UART_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==GPIO_UART_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==GPIO_UART_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/GPIO_UART/ip/GPIO_UART_ilmb_bram_if_cntlr_0/GPIO_UART_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==GPIO_UART_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==GPIO_UART_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/GPIO_UART/ip/GPIO_UART_lmb_bram_0/GPIO_UART_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==GPIO_UART_lmb_bram_0 || ORIG_REF_NAME==GPIO_UART_lmb_bram_0} -quiet] -quiet

# IP: bd/GPIO_UART/ip/GPIO_UART_clk_wiz_0_0/GPIO_UART_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==GPIO_UART_clk_wiz_0_0 || ORIG_REF_NAME==GPIO_UART_clk_wiz_0_0} -quiet] -quiet

# IP: bd/GPIO_UART/ip/GPIO_UART_NOT_0_0/GPIO_UART_NOT_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==GPIO_UART_NOT_0_0 || ORIG_REF_NAME==GPIO_UART_NOT_0_0} -quiet] -quiet

# IP: bd/GPIO_UART/ip/GPIO_UART_axi_gpio_1_0/GPIO_UART_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==GPIO_UART_axi_gpio_1_0 || ORIG_REF_NAME==GPIO_UART_axi_gpio_1_0} -quiet] -quiet

# XDC: bd/GPIO_UART/GPIO_UART_ooc.xdc
